# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=250)),
                ('MIDDLENAME', models.CharField(max_length=250)),
                ('SURNAME', models.CharField(max_length=250)),
                ('MOBILE', models.IntegerField(max_length=10)),
                ('EMAIL', models.CharField(max_length=250)),
            ],
        ),
    ]
