# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_member_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='User',
        ),
    ]
